---
- name: Update system packages
  apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes

- name: Install system dependencies
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
      - python3-dev
      - git
      - libopencv-dev
      - python3-opencv
      - libgl1-mesa-glx
      - libglib2.0-0
      - libsm6
      - libxext6
      - libxrender-dev
      - libgomp1
      - libgstreamer1.0-0
      - libgstreamer-plugins-base1.0-0
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - libv4l-dev
      - libxvidcore-dev
      - libx264-dev
      - libjpeg-dev
      - libpng-dev
      - libtiff-dev
      - libatlas-base-dev
      - gfortran
      - wget
      - curl
    state: present

- name: Create katzenschreck user if not exists
  user:
    name: "{{ katzenschreck_user }}"
    system: no
    shell: /bin/bash
    home: "/home/{{ katzenschreck_user }}"
    create_home: yes
  when: katzenschreck_user != "pi"

- name: Create katzenschreck directory
  file:
    path: "{{ katzenschreck_dir }}"
    state: directory
    owner: "{{ katzenschreck_user }}"
    group: "{{ katzenschreck_user }}"
    mode: '0755'

- name: Set up log directory
  file:
    path: "{{ katzenschreck_dir }}/logs"
    state: directory
    owner: "{{ katzenschreck_user }}"
    group: "{{ katzenschreck_user }}"
    mode: '0755'

- name: Set up results directory
  file:
    path: "{{ katzenschreck_dir }}/results"
    state: directory
    owner: "{{ katzenschreck_user }}"
    group: "{{ katzenschreck_user }}"
    mode: '0755'

