stages:       
  - build


build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - docker
  script:
    - echo "Compiling the code..."
    - python --version  # Optional: Check Python version
    - cd ipcam-detector
    - apt install pip
    - pip install -r requirements.txt  # Install dependencies
    - python main.py