# .gitlab-ci.yml

# Docker build image for Raspberry Pi 4 (ARM architecture)
image: docker:latest
#image: docker:linux/arm/v7

# Docker-in-Docker service to execute Docker commands
services:
  - docker:dind

# Variables for Docker registry and image
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:latest  # Automatically uses GitLab registry URL

# Job for authentication and building & pushing Docker image
build_and_push:
  stage: build
  tags: 
    - docker
  script:
    # Login to GitLab registry
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

    # Build Docker image for ARM (Raspberry Pi)
    - docker build -t $DOCKER_IMAGE --platform linux/arm/v7 .
    #- docker build -t $DOCKER_IMAGE .

    # Push Docker image to GitLab registry
    - docker push $DOCKER_IMAGE
  only:
    - main  # This job runs only on the 'main' branch